<?xml version="1.0" encoding="utf-8"?><Database Name="Database1" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=|DataDirectory|\Database1.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="Database1ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Booking" Member="Bookings">
    <Type Name="Booking">
      <Column Name="check_out" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="no_children" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="no_adult" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="check_in" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="room_type" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Customer_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="USERNAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EMAIL" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PASSWORD" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="GENDER" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>